app9/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = 'app9'

# Create your views here.
urlpatterns = [
    path('', views.index, name="app9index"),
    path('register/', views.register, name='app9register')
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include
from app9 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app9.urls')),
    path('', include("django.contrib.auth.urls"))
]

app9/models.py
from django.db import models

# Create your models here.

app9/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    class Meta:
        model = User 
        fields = [  
            'username', 
            'first_name',
            'last_name',
            'email', 
            'password1', 
            'password2',
        ]

app9/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = RegisterForm()
    
    return render(request,'register.html',{'form':form})

def index(request):
    # username = User.get_username()
    return render(request,'index.html')

app9/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Meta Tags-->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <!-- CSS Files-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Open+Sans&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous"/>
        <script src="https://kit.fontawesome.com/1f06dfeacc.js" crossorigin="anonymous"></script>

        {% if title %}
        <title>{{ title }}</title>
        {% else %}
        <title>Story 9</title>
        {% endif %}
    </head>
    <body style="text-align: center; background-color: #000000;">
        <!-- Content Start -->
        <div class="container" style="font-family: 'Roboto', sans-serif; padding: 2vh;">
            {% block content %} {% endblock content %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
    <!-- AJAX JSON Filler Script -->
    <script src="{% static 'scripts/main.js' %}"></script>
</html>

app9/templates/index.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
<h1>Home Page</h1>

{% if user.is_authenticated %}
<h3>Hello {{request.user.username}}</h3>
<p><a href="{% url 'logout' %}">Logout</a></p>

{% else %}
<p>Please login first.</p>
<p><a href="{% url 'login' %}">Login</a></p>
{% endif %} 
{% endblock content %}

app9/templates/register.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 
{% load static %}
{% block content %}
<!-- If user is logged in -->
{% if user.is_authenticated %}
<h3>Hi {{request.user.username}}, you are already logged in</h3>
<p>Go to <a href="{% url 'app9:app9index'%}">homepage</a></p>
<p>To register a new account, please <a href="{% url 'logout'%}">Logout</a></p>
{% else %}
<form method="POST" class="form-group">
    {% csrf_token %} {{form|crispy}}
    <button class="btn btn-success" type="submit">Register</button>
</form>
{% endif %} 
{% endblock content %}